I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 115, in script
    with distortion
  File "game/script.rpy", line 115, in <module>
    with distortion
NameError: name 'distortion' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 115, in script
    with distortion
  File "renpy/ast.py", line 1390, in execute
    trans = renpy.python.py_eval(self.expr)
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 115, in <module>
    with distortion
NameError: name 'distortion' is not defined

Windows-10-10.0.17763
Ren'Py 7.4.2.1292
rubens;GATE 1.0
Sat Feb 27 18:39:03 2021
